import { useCallback, useMemo, useRef } from "react";

export const Buttons = (props: { id: string }) => {
  const onClick = useCallback((buttonName:string) => {
      console.log(props.id, buttonName);
    },
    [props.id],
  );

  const autoGeneratedIds = useMemo<string[]>(() => {
    // generate 100 random string uuid's
    return Array.from({ length: 100 }, () =>
      Math.random().toString(36).substr(2, 9)
    );
  }, []);

    const id = useRef<string>();
    id.current = "Random value!";

    const divRef = useRef(null);

  return (
    <p ref={divRef}>
      <button onClick={() => onClick("A")}>A</button>
      <button onClick={() => onClick("B")}>B</button>
      <button onClick={() => onClick("C")}>C</button>
    </p>
  );
};


